-- https://www.reddit.com/r/neovim/comments/xhtr1p/nvim_autocmd_filetype_option/
-- vim.api.nvim_create_autocmd('BufWritePre', {
--   desc = 'format python on write using black',

--   group = vim.api.nvim_create_augroup('black_on_save', { clear = true }),
--   callback = function (opts)
--     if vim.bo[opts.buf].filetype == 'python' then
--       vim.cmd 'FormatPython'
--     end
--   end,
-- })
